name: Image Build to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push site image
        id: site_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/counter-site:latest

      - name: Site Image digest
        run: echo ${{ steps.site_build.outputs.digest }}
        
      - name: Build and push API image
        id: api_build
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/counter-api:latest

      - name: API Image digest
        run: echo ${{ steps.api_build.outputs.digest }}
